services:
  - type: web
    name: mzu-rag-api
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api:app --bind 0.0.0.0:10000"

    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_AUTH_TOKEN
        sync: false
